name: Build Aria2 Windows Binary

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build Docker image
      run: |
        docker build -t aria2-mingw -f Dockerfile.mingw .

    - name: Create output directory
      run: mkdir -p output

    - name: Copy binary from container
      run: |
        docker run --rm -v ${{ github.workspace }}/output:/out aria2-mingw \
        cp /aria2/src/aria2c.exe /out/

    - name: Upload aria2c.exe artifact
      uses: actions/upload-artifact@v3
      with:
        name: aria2-windows-binary
        path: output/aria2c.exe
